### ISSUE TITLE
bidspm

### ISSUE THREAD

**Issue by Remi-Gau** [bids-apps/bids-apps.github.io#81]
### Your BIDS app

```yml
  - gh: "cpp-lln-lab/bidspm"
    dh: "cpplab/bidspm"
    ci: "gh"
    branch: "main"
    workflow: "test"
    ds_type:
      - raw
      - derivative
    datatype:
      - anat
      - func
 ```

### Submission checklist

- [X] complies to the BIDS app API
- [X] has a system-test workflow set up
- [X] test dataset is validated before processing
