### ISSUE TITLE
bidsmreye

### ISSUE THREAD

**Issue by Remi-Gau** [bids-apps/bids-apps.github.io#82]
### Your BIDS app

```yml
  - gh: "cpp-lln-lab/bidsMReye"
    dh: "cpplab/bidsmreye"
    ci: "gh"
    branch: "main"
    workflow: "test"
    ds_type:
      - raw
    datatype:
      - func
```

### Submission checklist

- [X] complies to the BIDS app API
- [X] has a system-test workflow set up
- [ ] test dataset is validated before processing
